name: myanimestats-deploy

services:
  app:
    image: ghcr.io/titouan-lacombe/myanimestats:main
    restart: always
    environment:
      TZ: Europe/Paris
      PUID: $PUID
      PGID: $PGID
      LOG_LEVEL: DEBUG
      # ALLOW_IMPORT: "true"
    volumes:
      - ./data:/app/data
    labels:
      - traefik.enable=true
      - traefik.http.services.polybot-$ENV.loadbalancer.server.port=8000
      # - traefik.http.services.polybot-$ENV.loadbalancer.healthcheck.path=/health/
      - traefik.http.services.polybot-$ENV.loadbalancer.healthcheck.hostname=$APP_DOMAIN
      - traefik.http.routers.polybot-$ENV.rule=Host(`$APP_DOMAIN`)
      - traefik.http.routers.polybot-$ENV.entrypoints=websecure
      - traefik.http.routers.polybot-$ENV.tls=true
